PCM-1440
MyPureCloud/genesys-cloud-webrtc-sdk pull request #292
Opened 2020-10-05 18:23 UTC by djhouseknecht

changed gUM constraints to use ideal deviceId to avoid NotFound errors. added logs

2020-10-05 18:25 UTC, djhouseknecht commented
Most of these changes are for logging. The main change happens in [media-utils.ts](https://github.com/MyPureCloud/genesys-cloud-webrtc-sdk/pull/292/files#diff-e56c81e07d3028b35e2bed82adaf037b)

2020-10-05 19:00 UTC, kglawrence approved these changes
🔥 - So many logs!!

2020-10-06 15:39 UTC, jensengar requested changes

2020-10-06 16:24 UTC, djhouseknecht commented on src/media-utils.ts
> +  const sessionIds: Array<{ conversationId: string, sessionId: string }> =
Most definitely. I was struggling to find a name for this.

2020-10-07 14:34 UTC, jensengar approved these changes

2020-10-07 15:15 UTC, merged