no-jira adjusted rejection condition to ignore persistent connection and reject for all active sessions
MyPureCloud/genesys-cloud-webrtc-sdk pull request #842
Opened 2024-03-05 16:00 UTC by maxwellmooney13

2024-03-05 21:14 UTC, jensengar approved these changes

2024-03-05 21:48 UTC, zservies requested changes
Changelog

2024-03-06 00:50 UTC, hjon approved these changes

2024-03-06 14:27 UTC, zservies approved these changes

2024-03-06 14:28 UTC, merged