prep release 9.2.2
MyPureCloud/genesys-cloud-webrtc-sdk pull request #881
Opened 2024-09-10 19:13 UTC by jensengar

2024-09-10 19:28 UTC, maxwellmooney13 approved these changes

2024-09-10 21:58 UTC, hjon requested changes

2024-09-10 21:58 UTC, hjon commented on changelog.md
> +* [STREAM-191](https://inindca.atlassian.net/browse/STREAM-191) - Fix for slow performance of `pruneConversationUpdateForLogging`
These should be under v9.2.2.

2024-09-12 14:59 UTC, hjon approved these changes

2024-09-13 01:27 UTC, RobinsonWM approved these changes

2024-09-13 13:09 UTC, merged